image: node:10.15.3

cache:
  paths:
  - node_modules/

stages:
  - test

variables:
  AWS_DEFAULT_REGION: "us-east-1"
  EB_APP_NAME: "vault-pam-ui"
  EB_APP_ENV: "development"
  ZIP_FILE: "vault-pam-ui.zip"
  S3_BUCKET: "elasticbeanstalk-us-east-1-163714151155"
  S3_KEY: ""

# Executes eslint and runs unit tests.
test:
  stage: test
  before_script:
    - echo Installing AWS CLI
    - apt-get install -y python-dev python-pip
    - pip install awscli --ignore-installed six
  script:
    - ./scripts/deploy
