.common_template: &branch_definition
  only:
    - develop

.node_template: &node_definition
  image: node:10.15.3
  cache:
    paths:
    - node_modules/

.python_template: &python_definition
  image: python:3.5
  before_script:
    - echo Installing AWS CLI
    - pip install awscli --ignore-installed six

stages:
  - test
  - build
  - upload
  - create_app
  - deploy

# Executes eslint and runs unit tests.
test:
  <<: *node_definition
  stage: test
  <<: *branch_definition
  script:
    - npm install
    - npm run lint
    - npm test -- --coverage
  artifacts:
    paths:
      - coverage/

# Builds the application and zips it up.
build:
  <<: *node_definition
  stage: build
  <<: *branch_definition
  script:
    - npm run build
  artifacts:
    paths:
    - vault-pam-ui.zip
    expire_in: 15 mins

upload:
  <<: *python_definition
  stage: upload
  <<: *branch_definition
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    EB_APP_NAME: "vault-pam-ui"
    ZIP_FILE: "vault-pam-ui.zip"
    S3_BUCKET: "elasticbeanstalk-us-east-1-163714151155"
  before_script:
    - echo Installing AWS CLI
    - pip install awscli --ignore-installed six
  script:
    - export BUILD_VERSION=`date "+%Y-%m-%d-%H-%M-%S"`
    - echo Setting build version to $BUILD_VERSION
    - export VERSIONED_ZIP_FILE=$BUILD_VERSION.zip
    - echo BUILD_VERSION=$BUILD_VERSION >> build_vars
    - echo VERSIONED_ZIP_FILE=$VERSIONED_ZIP_FILE >> build_vars
    - echo S3_BUCKET=$S3_BUCKET >> build_vars
    - echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> build_vars
    - echo EB_APP_NAME=$EB_APP_NAME >> build_vars
    - echo Renaming $ZIP_FILE to $VERSIONED_ZIP_FILE
    - mv $ZIP_FILE $VERSIONED_ZIP_FILE
    - aws s3 cp $VERSIONED_ZIP_FILE "s3://$S3_BUCKET"
  artifacts:
    paths:
      - build_vars
    expire_in: 15 mins

# Deploys the zip to Elastic Beanstalk and create the application.
create_app:
  <<: *python_definition
  stage: create_app
  <<: *branch_definition
  script:
    - source build_vars
    - export BUILD_VERSION
    - export VERSIONED_ZIP_FILE
    - export S3_BUCKET
    - export AWS_DEFAULT_REGION
    - export EB_APP_NAME
    - export EB_VERSION=v.$BUILD_VERSION
    - echo Creating ElasticBeanstalk Application Version $EB_VERSION
    - aws elasticbeanstalk create-application-version --application-name $EB_APP_NAME --version-label $EB_VERSION --source-bundle S3Bucket=$S3_BUCKET,S3Key=$VERSIONED_ZIP_FILE --auto-create-application
    - echo Application Created!

# Update the enterprise Elastic Beanstalk environment with the latest build.
deploy_enterprise:
  <<: *python_definition
  stage: deploy
  <<: *branch_definition
  variables:
    EB_APP_ENV: "development"
  script:
    - source build_vars
    - export BUILD_VERSION
    - export VERSIONED_ZIP_FILE
    - export S3_BUCKET
    - export AWS_DEFAULT_REGION
    - export EB_APP_NAME
    - export EB_VERSION=v.$BUILD_VERSION
    - echo Updating ElasticBeanstalk Application Version $EB_VERSION Environment $EB_APP_ENV
    - aws elasticbeanstalk update-environment --application-name $EB_APP_NAME --environment-name $EB_APP_ENV --version-label $EB_VERSION --option-settings Namespace=aws:elasticbeanstalk:application:environment,OptionName=EB_VERSION,Value=$EB_VERSION
    - echo Done! Deployed!

# Update the standard Elastic Beanstalk environment with the latest build.
deploy_standard:
  <<: *python_definition
  stage: deploy
  <<: *branch_definition
  variables:
    EB_APP_ENV: "development-standard"
  script:
    - source build_vars
    - export BUILD_VERSION
    - export VERSIONED_ZIP_FILE
    - export S3_BUCKET
    - export AWS_DEFAULT_REGION
    - export EB_APP_NAME
    - export EB_VERSION=v.$BUILD_VERSION
    - echo Updating ElasticBeanstalk Application Version $EB_VERSION Environment $EB_APP_ENV
    - aws elasticbeanstalk update-environment --application-name $EB_APP_NAME --environment-name $EB_APP_ENV --version-label $EB_VERSION --option-settings Namespace=aws:elasticbeanstalk:application:environment,OptionName=EB_VERSION,Value=$EB_VERSION
    - echo Done! Deployed!

pages:
  stage: build
  dependencies:
    - test
  script:
    - ls -l
    - ls coverage -l
    - rm -rf public
    - mv coverage/lcov-report/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  <<: *branch_definition
