image: python:3.5

stages:
  - test

variables:
  AWS_DEFAULT_REGION: "us-east-1"
  EB_APP_NAME: "vault-pam-ui"
  EB_APP_ENV: "development"
  ZIP_FILE: "vault-pam-ui.zip"
  S3_BUCKET: "elasticbeanstalk-us-east-1-163714151155"
  S3_KEY: ""

# Executes eslint and runs unit tests.
test:
  stage: test
  before_script:
    - echo Installing AWS CLI
    - curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
    - python get-pip.py
    - pip install awscli --ignore-installed six
  script:
    - ./scripts/deploy
