image: node:10.15.3

cache:
  paths:
  - node_modules/

stages:
  - test
  - build

test:
  stage: test
  script:
    - npm install
    - npm run lint
    - npm test -- --coverage

build:
  stage: build
  script:
    - npm run build
