image: node:10.15.3

cache:
  paths:
  - node_modules/

stages:
  - test
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: "us-east-1"
  EB_APP_NAME: "vault-pam-ui"
  EB_APP_ENV: "development"
  ZIP_FILE: "vault-pam-ui.zip"
  S3_BUCKET: "elasticbeanstalk-us-east-1-163714151155"
  S3_KEY: ""

# Executes eslint and runs unit tests.
test:
  stage: test
  script:
    - npm install
    - npm run lint
    - npm test -- --coverage

# Builds the application and zips it up.
build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
    - vault-pam-ui.zip
    expire_in: 10 mins

# Deploys the zip to Elastic Beanstalk.
deploy:
  stage: deploy
  before_script:
    - echo Installing AWS CLI
    - apt-get install -yqq python-pip python3-dev
    - pip install awscli --ignore-installed six
  script:
    - ./scripts/deploy
