# Simple build configuration to run lint. For additional features, check out the Bitbucket guides at https://confluence.atlassian.com/x/14UWN for more examples.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm run lint
          - npm test -- --coverage
          - npm run build
        artifacts:
          - vault-web-ui.zip
    - step:
        name: "Deploy to Dev Environment"
        deployment: test
        script:
        - pipe: atlassian/aws-elasticbeanstalk-deploy:0.2.1
          variables:
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            AWS_DEFAULT_REGION: "us-east-1"
            APPLICATION_NAME: "vault-web-ui"
            ZIP_FILE: "vault-web-ui.zip"
            S3_BUCKET: "elasticbeanstalk-us-east-1-163714151155"
            VERSION_LABEL: "v-$BITBUCKET_BUILD_NUMBER-multiple"
