version: '3.5'

services:
    vault-pam-ui:
        container_name: vault-pam-ui
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
            - PAM_DATABASE=${PAM_DATABASE}
            - PAM_DATABASE_USER=${PAM_DATABASE_USER}
            - PAM_DATABASE_PASSWORD=${PAM_DATABASE_PASSWORD}
            - PAM_DATABASE_URL=${PAM_DATABASE_URL}
            - PAM_DATABASE_PORT=${PAM_DATABASE_PORT}
            - VAULT_API_TOKEN=${VAULT_API_TOKEN}
            - VAULT_DOMAIN=${VAULT_DOMAIN}
            - PAM_MAIL_SERVICE=${PAM_MAIL_SERVICE}
            - PAM_MAIL_USER=${PAM_MAIL_USER}
            - PAM_MAIL_PASS=${PAM_MAIL_PASS}